### ISSUE TITLE
`rapids-logger` missing date string?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/rapids-logger#27]
In the `integration` repo's nightly CI, we are seeing [the following error]( https://github.com/rapidsai/integration/actions/runs/13540165255/job/37839287279#step:9:13371 ):

```
Date string not found for rapids-logger in the build string 'h4a24d4e_0'.

Error: The following packages are missing dates in their build strings:
 - rapids-logger
```

**Comment by jakirkham** [comment]
Looking at [`librmm`'s recipe]( https://github.com/rapidsai/rmm/blob/01edf5a66819b30f8fd2409732f074df01ecdb1a/conda/recipes/librmm/recipe.yaml#L57 ), think we are looking for the following additions (though CUDA versioning may be unneeded here)

```yaml
context:
  ...
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: ${{ git.head_rev(".")[:8] }}

...

build:
  ...
  string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}

...
```
